### ISSUE TITLE
.NET number values such as positive and negative infinity cannot be written as valid JSON.

### ISSUE THREAD

**Issue by steveoh** [NetTopologySuite/NetTopologySuite.IO.GeoJSON#62]
I'm trying to serialize a feature with a dictionary and a point and receive this error. I'm not sure if it is related to bounding box or envelope with are empty. Any thoughts on whats up? Nice job on the standup otherwise I wouldn't have known about this library. I'm coming from geojson.net.

I tried this with just a point and it fails with the same message also so I would assume that the point is the cause of the issue.

`var feature = new Feature(new Point(1, 2), new AttributesTable());`

with

```csharp
.AddJsonOptions(options => {
                // open api is currently using system.text.json
                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
                options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault;
                options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
            });
```

```
[ERR 17:31:50] (Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware) An unhandled exception has occurred while executing the request. 
System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON.
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
   at System.Text.Json.Serialization.Converters.DoubleConverter.Write(Utf8JsonWriter writer, Double value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by steveoh** [comment]
forgot to add the converter... oops.

`options.JsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());`

maybe this will help someone in the future :)

**Comment by Pritts** [comment]
@steveoh My project doesn't have any converters within NetTopologySuite.IO.
Am I missing some NuGet Package?

**Comment by airbreather** [comment]
@Pritts check that you're referencing NetTopologySuite.IO.GeoJSON**4STJ**, instead of just NetTopologySuite.IO.GeoJSON.

The former is for `System.Text.Json`, which is what this is about; the bare ".GeoJSON" project is for Json.NET (Newtonsoft.Json).

**Comment by Pritts** [comment]
@airbreather That did it, thanks a lot! That was a bit confusing.

**Comment by airbreather** [comment]
> That was a bit confusing.

Sorry about that -- we named the bare ".GeoJSON" project when Json.NET was the only one around.

It didn't make sense to just add the `System.Text.Json` converters to the same project, since then you would have to reference two completely different JSON processing libraries, which would be confusing the whole time instead of just at the beginning 😉.

**Comment by kipusoep** [comment]
I'm confused. Trying to serialize an object with a `Coordinate` property. I can see the `Z` property of that coordinate is `NaN`.
Trying to serialize using the `GeoJsonConverterFactory` added to the converters doesn't help:

```c#
private readonly JsonSerializerOptions _geometryJsonSerializerOptions = new();

public Constructor()
{
    _geometryJsonSerializerOptions.Converters.Add(new GeoJsonConverterFactory());
}

var json = JsonSerializer.Serialize(data.SomeProp, data.SomeProp.GetType(), _geometryJsonSerializerOptions);
```

Result:
`.NET number values such as positive and negative infinity cannot be written as valid JSON.`

Anything I'm doing wrong?
Using NetTopologySuite.IO.GeoJSON4STJ 2.1.1

**Comment by kipusoep** [comment]
Alright so I noticed that the `Coorinate` class isn't included in the supported types list of the converter factory: https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/stj-v2.1.1/src/NetTopologySuite.IO.GeoJSON4STJ/Converters/GeoJsonConverterFactory.cs#L21
So I switched back to `Point` and now it works :-)

**Comment by szjabc** [comment]
thank you

**Comment by marcelloo96** [comment]
> @steveoh My project doesn't have any converters within NetTopologySuite.IO.
> Am I missing some NuGet Package?
That's in here
https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON

**Comment by mhosman** [comment]
I tried adding the converter, using GeoJson4STJ 3.0.0 and this is still not working.

`.NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling).`

i also added the AllowNamedFloatingPointLiterals but nothing. This is my config in the Program.cs:

```
AddJsonOptions(options =>
{
    options.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    options.JsonSerializerOptions.Converters.Add(new GeoJsonConverterFactory());
    options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals;
});
```

**Comment by crozone** [comment]
@mhosman I am also seeing this exact behaviour. I have:

```
builder.Services.AddMvc(config =>
{
    // Prevent the following exception: 'This method does not support GeometryCollection arguments' 
    // See: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/585
    config.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Point)));
    config.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(Coordinate)));
    config.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(LineString)));
    config.ModelMetadataDetailsProviders.Add(new SuppressChildValidationMetadataProvider(typeof(MultiLineString)));
})
.AddJsonOptions(configure =>
{
    // Add NetTopologySuite GeoJSON converter
    configure.JsonSerializerOptions.Converters.Add(new NetTopologySuite.IO.Converters.GeoJsonConverterFactory());
})
```

Yet I still get the exception returned

> ".NET number values such as positive and negative infinity cannot be written as valid JSON. To make it work when using 'JsonSerializer', consider specifying 'JsonNumberHandling.AllowNamedFloatingPointLiterals' (see https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonnumberhandling)."

**Comment by crozone** [comment]
@mhosman I had the same issue but figured it out.

Deserialization coming into the controller action wasn't actually the issue, my code was doing some manual serialization and deserialization of a type that contained an `IFeature` property.

For this to work, you need to pass in a `JsonSerializerOptions` that contains the `GeoJsonConverterFactory()`. To get the configuration that was set up with `AddJsonOptions()` back out of the DI pipeline, inject `IOptions<JsonOptions> jsonOptions` to the controller or service.

Then serialize the data with:

`JsonSerializer.Serialize(dataObject, options: jsonOptions.Value.JsonSerializerOptions) `
